export enum AuthenticationConstants {
    AUTH_LOGIN = "AUTH_LOGIN",
    AUTH_LOGIN_PENDING = "AUTH_LOGIN_PENDING",
    AUTH_LOGIN_FULFILLED = "AUTH_LOGIN_FULFILLED",
    AUTH_LOGIN_REJECTED = "AUTH_LOGIN_REJECTED",
    AUTH_LOGOUT = "AUTH_LOGOUT"
}
