export enum ConfigurationConstants {
    CONFIGURATION_LOADING = "CONFIGURATION_LOADING",
    CONFIGURATION_LOADING_PENDING = "CONFIGURATION_LOADING_PENDING",
    CONFIGURATION_LOADING_REJECTED = "CONFIGURATION_LOADING_REJECTED",
    CONFIGURATION_LOADING_FULFILLED = "CONFIGURATION_LOADING_FULFILLED",
    CONFIGURATION_LOADING_SUCCESS = "CONFIGURATION_LOADING_SUCCESS"
}
