export enum DepositConstants {
    FETCH_DEPOSITS = "FETCH_DEPOSITS",
    FETCH_DEPOSITS_PENDING = "FETCH_DEPOSITS_PENDING",
    FETCH_DEPOSITS_FULFILLED = "FETCH_DEPOSITS_FULFILLED",
    FETCH_DEPOSITS_REJECTED = "FETCH_DEPOSITS_REJECTED",

    CLEAN_DEPOSITS = "CLEAN_DEPOSITS",

    DELETE_DEPOSIT = "DELETE_DEPOSIT",
    DELETE_DEPOSIT_PENDING = "DELETE_DEPOSIT_PENDING",
    DELETE_DEPOSIT_FULFILLED = "DELETE_DEPOSIT_FULFILLED",
    DELETE_DEPOSIT_REJECTED = "DELETE_DEPOSIT_REJECTED",
}
