export enum DepositConstants {
    FETCH_DEPOSITS = "FETCH_DEPOSITS",
    FETCH_DEPOSITS_PENDING = "FETCH_DEPOSITS_PENDING",
    FETCH_DEPOSITS_FULFILLED = "FETCH_DEPOSITS_FULFILLED",
    FETCH_DEPOSITS_REJECTED = "FETCH_DEPOSITS_REJECTED",
    CLEAN_DEPOSITS = "CLEAN_DEPOSITS",
}
