export enum DepositFormConstants {
    SET_DEPOSIT_ID = "SET_DEPOSIT_ID",

    FETCH_METADATA = "FETCH_METADATA",
    FETCH_METADATA_PENDING = "FETCH_METADATA_PENDING",
    FETCH_METADATA_FULFILLED = "FETCH_METADATA_FULFILLED",
    FETCH_METADATA_REJECTED = "FETCH_METADATA_REJECTED",
    FETCH_METADATA_SUCCEEDED = "FETCH_METADATA_SUCCEEDED",
    FETCH_METADATA_FAILED = "FETCH_METADATA_FAILED",

    SAVE_DRAFT = "SAVE_DRAFT",
    SAVE_DRAFT_PENDING = "SAVE_DRAFT_PENDING",
    SAVE_DRAFT_FULFILLED = "SAVE_DRAFT_FULFILLED",
    SAVE_DRAFT_REJECTED = "SAVE_DRAFT_REJECTED",
    SAVE_DRAFT_FAILED = "SAVE_DRAFT_FAILED",

    SUBMIT_DEPOSIT = "SUBMIT_DEPOSIT",
    SUBMIT_DEPOSIT_PENDING = "SUBMIT_DEPOSIT_PENDING",
    SUBMIT_DEPOSIT_FULFILLED = "SUBMIT_DEPOSIT_FULFILLED",
    SUBMIT_DEPOSIT_REJECTED = "SUBMIT_DEPOSIT_REJECTED",
    SUBMIT_DEPOSIT_FAILED = "SUBMIT_DEPOSIT_FAILED",
}
