export enum DropdownConstants {
    FETCH_AUDIENCE_DROPDOWN = "FETCH_AUDIENCE_DROPDOWN",
    FETCH_AUDIENCE_DROPDOWN_PENDING = "FETCH_AUDIENCE_DROPDOWN_PENDING",
    FETCH_AUDIENCE_DROPDOWN_FULFILLED = "FETCH_AUDIENCE_DROPDOWN_FULFILLED",
    FETCH_AUDIENCE_DROPDOWN_REJECTED = "FETCH_AUDIENCE_DROPDOWN_REJECTED",
    FETCH_AUDIENCE_DROPDOWN_FAILED = "FETCH_AUDIENCE_DROPDOWN_FAILED",
}
