export enum UserConstants {
    USER= "USER",
    USER_FAILED="USER_FAILED",
    USER_SUCCESS = "USER_SUCCESS",
    USER_PENDING = "USER_PENDING",
    USER_FULFILLED = "USER_FULFILLED",
    USER_REJECTED = "USER_REJECTED",
}